start_button=['..\\images\\start.png','..\\images\\start_down.png']
paihang_button=['..\\images\\paihang.png','..\\images\\paihang_down.png']
histroy_button=['..\\images\\his.png','..\\images\\his_down.png']
background='..\\images\\background.png'
again_button=['..\\images\\again.png','..\\images\\again_down.png']
gameover_button=['..\\images\\gameover.png','..\\images\\gameover_down.png']
enenmy1='..\\images\\enemy1.png'
enenmy1_down=[
        '..\\images\\enemy1_down1.png',
        '..\\images\\enemy1_down2.png',
        '..\\images\\enemy1_down3.png',
         ]
enenmy2='..\\images\\enemy2.png'
enenmy2_down=[
        '..\\images\\enemy2_down1.png',
        '..\\images\\enemy2_down2.png',
        '..\\images\\enemy2_down3.png',
        '..\\images\\enemy2_down4.png'
         ]
enenmy2_hit=[enenmy2,'..\\images\\enemy2_hit.png']
enenmy3='..\\images\\enemy3_n1.png'
enenmy3_down=[
        '..\\images\\enemy3_down1.png',
        '..\\images\\enemy3_down2.png',
        '..\\images\\enemy3_down3.png',
        '..\\images\\enemy3_down4.png',
        '..\\images\\enemy3_down5.png',
'..\\images\\enemy3_down6.png'
         ]
enenmy3_hit=[enenmy3,'..\\images\\enemy3_hit.png']
pause=['..\\images\\pause_nor.png','..\\images\\pause_pressed.png']
resume=['..\\images\\resume_nor.png','..\\images\\resume_pressed.png']
